PlayerData/react-native-mcu-manager

- package.json
See https://semantic-release.gitbook.io/semantic-release/support/faq#how-can-i-set-the-access-level-of-the-published-npm-package
> Allow public publish

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/McuManagerModule.kt
Android simulator wasn't working because the default adapter was null. This isn't a problem for just running the app though so we have made this nullable and checked that it isn't null before using it in the function below. 
resolves https://github.com/PlayerData/app/issues/2533
Self Review:
Smoke Tests:
> fix(android): check for nulls in getDefaultAdapter

- ios/McuManager.swift
Fixes build error:
```
'super.init' isn't called on all paths before returning from initializer
```
Ref https://github.com/PlayerData/app/pull/2876
Self Review:
Smoke Tests:
> fix: Always call super.init

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/McuManagerModule.kt
Removes warnings about event listeners for RN 0.65+:
```
new NativeEventEmitter() was called with a non-null argument without the required addListener/removeListeners method.
```
See https://github.com/software-mansion/react-native-reanimated/pull/2316
There's little documentation, but there doesn't appear to be any need to do anything in the methods.
Self Review:
Smoke Tests:
> Add listener stubs for RN 0.65+

- android/build.gradle
- android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpdate.kt
- example/src/App.tsx
- example/src/useBluetoothDevices.ts
- example/src/useFirmwareUpdate.ts
- example/tsconfig.json
- ios/DeviceUpdate.swift
- src/index.tsx
Allows the upgrade mode to be selected when upgrading.
Also includes minor changes to the example app:
* Allow selecting of upgrade mode
* Move device selection into a modal
* Sort devices by name
Self Review:
Smoke Tests:
> Add UpgradeMode to interface

- example/ios/Podfile.lock
- ios/DeviceUpgrade.swift
- react-native-mcu-manager.podspec
Upstream `McuManager` has been renamed to `iOSMcuManagerLibrary`
Self Review:
Smoke Tests:
> Upgrade iOSMcuManagerLibrary

- android/build.gradle
Fixes #23 
Upstream has now released a version including the patch for running updates on devices on the correct image already
Self Review:
Smoke Tests:
> chore(android): switch back to official mcumgr library

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/McuManagerModule.kt
- example/src/App.tsx
- example/src/useFirmwareUpdate.ts
Ref https://github.com/PlayerData/app/issues/4749
The `cancelUpgrade` function on Android is incorrectly called `cancel`, meaning it isn't available to JavaScript.
Also adds a cancel button to the example app to prove this.
Self Review:
Smoke Tests:
> Correct cancelUpgrade function name

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
React native `null`s out the underlying promise reject/resolve objects once a promise has been resolved/rejected.
We're seeing a race between `cancel` calls that causes the promise to be resolved/rejected twice.
By giving `withSafePromise` a `@Synchronized` annotation, we ensure it is only called by one thread per instance of `DeviceUpgrade`.
Strictly, changing the order of the block call / promiseComplete call is unnecessary, but it feels safer this way round.
Self Review:
Smoke Tests:
> Safer promise check

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/McuManagerModule.kt
- ios/McuManager.m
- ios/McuManager.swift
- src/index.tsx
Ref https://github.com/PlayerData/edge-v2/issues/542
Exposes the ability to erase an image.
Self Review:
Smoke Tests:
> Expose ability to erase secondary image

- src/index.tsx
`McuManager` can be undefined in tests.
Self Review:
Smoke Tests:
> Allow native module to be undefined (for test mocking)

- ios/McuManager.swift
Previously we were holding the connection, which causes timeouts if we then attempt to connect to more peripherals.
Self Review:
Smoke Tests:
> Request disconnect after erase operation

- android/build.gradle
ref: https://github.com/PlayerData/app/issues/5857
Getting the following error when trying to detox build for android. This should fix it.
```
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':playerdata_react-native-mcu-manager:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-android:0.71.3] /Users/williamflemmer/.gradle/caches/transforms-3/d812b33ccc5e387336320351cd36011d/transformed/jetified-react-android-0.71.3-debug/AndroidManifest.xml as the library might be using APIs not available in 16
Suggestion: use a compatible library with a minSdk of at most 16,
or increase this project's minSdk version to at least 21,
or use …
```
> fix(android): bump minSdkVersion from 16 to 21

- example/ios/Podfile.lock
- ios/DeviceUpgrade.swift
- ios/McuManager.swift
Relates to: https://github.com/PlayerData/react-native-mcu-manager/issues/56 and https://github.com/PlayerData/roadmap/issues/861
Wrap the body of the exposed async methods in the manner suggested on https://github.com/PlayerData/react-native-mcu-manager/issues/56 also updates the example app and squashes an xcode linter warning about missing self references.
Self Review:
Smoke Tests:
> Async wrap upgrade

- example/ios/Podfile.lock
- ios/DeviceUpgrade.swift
- react-native-mcu-manager.podspec
2f7be14ffc25bab9bcd15578ec3f2ccaafd106a2 and 8dd0b6a8e0363556a6c31e12737684c1426d9ccc
The issues with firmware upgrades appear to be coming from a query of mcmgr parameters on the device that is expected to fail but the library doesn't handle the failure correctly and crashes. recent prs to the libary suggest they might be trying to fix this issue but these haven't been published as a version yet and pr descriptions read like its an ongoing not fixed issue.
https://github.com/NordicSemiconductor/IOS-nRF-Connect-Device-Manager/pull/148/files
Self Review:
Smoke Tests:
> fix(ios): revert bump of iosmcumgr

- .github/workflows/build_and_release.yml
- example/package-lock.json
- example/package.json
We want to make sure the library does work or at least compiles correctly when added to an app by checking the prebuilt android and ios apps
Closes `Improve CI coverage for React Native MCU Mgr #71 `
I tried passing along the context of the first step but it would require so much stuff to be uploaded or cached across instances that it seems just faster to re-checkout and re-install the deps.
Self Review:
Smoke Tests:
> Adding prebuild and example apps build steps 

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
- android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuManagerModule.kt
- android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuMgrException.kt
Resolves https://github.com/PlayerData/react-native-mcu-manager/issues/99
Frustratingly, some of the Nordic defined errors do not have messages. This causes react native to throw "Value is null, expected a String".
Self Review:
Smoke Tests:
> fix(android): Ensure MCUMgr errors always have a message

- .github/workflows/build_and_release.yml
The last release failed because `expo-module` wasn't available:
https://github.com/PlayerData/react-native-mcu-manager/actions/runs/6824752081/job/18561705994
Self Review:
> fix: Ensure expo-module script is available in release step

- android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
- android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuMgrException.kt
- example/App.tsx
- example/src/useBluetoothDevices.ts
- ios/DeviceUpgrade.swift
- ios/ReactNativeMcuManager.podspec
- ios/ReactNativeMcuManagerModule.swift
- ios/UpdateOptions.swift
We want to benefit from the bugfixes and QOL changes in the iOS library (including better error handling and some improvements in upload throughput)
Updating to the latest version of the library means we need to do some changes in how the iOs version of the app works.
Now the start/pause/cancel operations need to be done in the main thread
Self Review:
Smoke Tests:
> Updating iOS MCU lib

- android/build.gradle
Update build.gradle to set sourceCompatibility and targetCompatibility to JavaVersion.VERSION_11 for AGP versions below 8
Added support for React Native 0.73
The build fails on React Native 0.73 for Android due to a Kotlin version inconsistency. This can be resolved by adhering to the [expo commit](https://github.com/expo/expo/commit/7ec55dfae4942ced223d1a67950e92ebf8f6c7e3) standard for Kotlin versioning
Self Review:
> EXT-FSS2 Added support for React Native 0.73

- ios/DeviceUpgrade.swift
- ios/ReactNativeMcuManager.podspec
- src/Upgrade.ts
Resolves https://github.com/PlayerData/roadmap/issues/1694
Ref https://github.com/PlayerData/roadmap/issues/1508
* Upgrades to latest upstream iOS release
* Filters events to the correct Upgrade ID
Self Review:
Smoke Tests:
> Filters events to the correct Upgrade ID

- react-native-mcu-manager/android/build.gradle
- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/ZipPackage.java
Use the files and logic from the original repo examples
fix #384 
Self Review:
Smoke Tests:
> feat(android): Support ZIP format

- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuManagerModule.kt
This means we can avoid use of the assertion operator.
Resolves https://github.com/PlayerData/roadmap/issues/2721
Self Review:
> fix(android): Safer null checks while retriving upgrade

- README.md
- example/src/useFirmwareUpdate.ts
- react-native-mcu-manager/ios/ReactNativeMcuManagerModule.swift
- react-native-mcu-manager/src/Upgrade.ts
As of https://github.com/PlayerData/react-native-mcu-manager/pull/425, we're not emitting any events. We can remove them all.
Self Review:
> Remove all events

- example/package.json
- example/src/App.tsx
- example/src/useFirmwareUpdate.ts
- pnpm-lock.yaml
- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuManagerModule.kt
- react-native-mcu-manager/ios/DeviceUpgrade.swift
- react-native-mcu-manager/ios/UpdateOptions.swift
- react-native-mcu-manager/src/Upgrade.ts
- react-native-mcu-manager/src/index.ts
- renovate.json
This avoids any ambiguity.
BREAKING CHANGE: UpgradeOptions must now include the upgrade file type
Self Review:
Smoke Tests:
> feat: Explicitly set either bin or zip upgrade file

- example/src/app/_layout.tsx
- example/src/app/bootloader_info.tsx
- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuManagerModule.kt
- react-native-mcu-manager/ios/BootloaderInfo.swift
- react-native-mcu-manager/ios/ReactNativeMcuManagerModule.swift
- react-native-mcu-manager/src/Upgrade.ts
- react-native-mcu-manager/src/bootloaderInfo.ts
- react-native-mcu-manager/src/index.ts
Allow us to fetch Bootloader info from the MCU.
This includes:
* Bootloader name
* MCUBoot mode
* MCUBoot `noDowngrade` flag
Self Review:
Smoke Tests:
> feat: Add bootloader info

- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/DeviceUpgrade.kt
- react-native-mcu-manager/ios/DeviceUpgrade.swift
- react-native-mcu-manager/src/Upgrade.ts
We claimed to support "NONE" mode, but we didn't actually implement this properly.
This adds support for NONE mode.
Self Review:
Smoke Tests:
> feat: Add upload only mode

- react-native-mcu-manager/android/src/main/java/uk/co/playerdata/reactnativemcumanager/ReactNativeMcuManagerModule.kt
- react-native-mcu-manager/ios/DeviceUpgrade.swift
- react-native-mcu-manager/ios/UpdateOptions.swift
- react-native-mcu-manager/src/Upgrade.ts
Allowing TypeScript to pass `eraseAppSettings` as part of `UpgradeOptions`, so that we can have more control if we want to erase app settings or not
Currently, there is no way of erasing App settings as part of the MCU manager firmware update.
This is because this is handled by a boolean `eraseAppSettings` and its set to `false`. 
By allowing it to pass it via `UpgradeOptions`, we can have more control
Self Review:
Smoke Tests:
> Adding eraseAppSettings to UpgradeOptions TypeScript type
